### ISSUE TITLE
Missing code style guidelines

### ISSUE THREAD

**Issue by etse** [holgerl/hilvl#5] opened 2015-09-20 21:01 UTC
I reccomend adding a few guidelines for the pull-requests.
Function names, camelCase versus underscore_sepearated?
tabs: 4 spaces or \t?
is ES6 allowed?

**Comment by holgerl** [comment] 2015-09-22 07:50
Closed as duplicate of https://github.com/holgerl/hilvl/issues/6

Added your comment to that issue

**Closed as completed by holgerl** 2015-09-22 07:50 UTC
